version: "3.9"
services:
  standalone:
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
  app:
    build: .
    environment:
      CHROME_STANDALONE: "http://standalone:4444/wd/hub"
    depends_on:
      - standalone